services:
  python-ebics-api-client-python:
    container_name: python-ebics-api-client-python
    build:
      context: python
    volumes:
      - ../:/var/www/ebics-api-client-python/
      - /var/www/ebics-api-client-python/docker
    extra_hosts:
      - "ebics-api-client.local:172.17.0.1"
    tty: true
    networks:
      ebics-api-client-python-net:
        ipv4_address: 172.129.0.6

networks:
  ebics-api-client-python-net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.129.0.0/24
    driver_opts:
      com.docker.network.bridge.name: br_eacp